version: "3.3"

services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    build: docker/php
    #restart: always
    #working_dir: /app
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    environment:
      - PHP_ENABLE_XDEBUG=${PHP_ENABLE_XDEBUG}
      #- XDEBUG_CONFIG=client_host=127.0.0.1 client_port=9005
      #- PHP_IDE_CONFIG=serverName=Example
  cron:
    container_name: ${COMPOSE_PROJECT_NAME}-cron
    build:
      context: docker/cron
      args:
        - COMPOSE_PROJECT_NAME
    depends_on:
      - php
    volumes:
      - .:/app
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    build: docker/nginx
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - .:/app
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  pgadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.loc
      PGADMIN_DEFAULT_PASSWORD: password
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:6.2-alpine
    #command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  phpredisadmin:
    container_name: ${COMPOSE_PROJECT_NAME}-phpredisadmin
    image: erikdubbelboer/phpredisadmin
    depends_on:
      - redis
    ports:
      - 5080:80
    environment:
      ADMIN_USER: admin
      ADMIN_PASS: password
      REDIS_1_HOST: ${REDIS_HOST}
      REDIS_1_PORT: ${REDIS_PORT}

volumes:
  postgres_data:
    #driver: local
  redis_data:
